[general]
enabled = yes
pretty = yes
allowed_origins = *
websocket_write_timeout = 100

[asterisk]
type = user
read_only = no
password = supersecret123
# password can be plaintext for dev; in prod use password_format=plain or hashed
